language: go
sudo: required

go:
    - 1.11

env:
    - GO111MODULE=on

go_import_path: github.com/clearlinux/mixer-tools

services:
    - docker

before_install:
    - sudo apt-get update -qq
    - curl -L https://git.io/vp6lP | sh
    - docker build -t testdock .

script:
    - make lint
    - make check
    - docker run testdock
