language: go
sudo: required

go:
    - 1.9

go_import_path: github.com/clearlinux/mixer-tools

before_install:
    - sudo apt-get update -qq
    - go get -u gopkg.in/alecthomas/gometalinter.v1
    - gometalinter.v1 --install

script:
    - make lint
