#!/bin/sh
echo "Inside initramfs init..."
bin/mount -t proc none /proc
bin/mount -t sysfs none /sys
bin/mount -t devtmpfs none /dev
echo "Executing veritysetup..."
bin/veritysetup --verbose --data-block-size=1024 --hash-block-size=1024 create root /dev/vda3 /dev/vda4 275178934767540a0db04f0c354825739b9763380d5e039b31d179b7c11d5755
bin/sleep 10
bin/mount /dev/mapper/root /mnt/root
bin/mount --move /proc /mnt/root/proc
bin/mount --move /sys /mnt/root/sys
bin/mount --move /dev /mnt/root/dev
echo "Executing switch_root..."
exec bin/switch_root /mnt/root /usr/lib/systemd/systemd-bootchart