#!/bin/sh
echo "Inside initramfs init..."
bin/mount -t proc none /proc
bin/mount -t sysfs none /sys
bin/mount -t devtmpfs none /dev
bin/mount -t tmpfs none /run

echo "Executing veritysetup..."
bin/veritysetup --verbose --data-block-size=1024 --hash-block-size=1024 create root /dev/vda3 /dev/vda4 234726bc436ff06e55387e648e7c091e6fd4aab83bfe4d0e9acf64fb2d9642f9
bin/sleep 0.25
bin/mount /dev/mapper/root /mnt/root

bin/mount -t tmpfs tmpfs /mnt/root/etc
bin/mount -t tmpfs tmpfs /mnt/root/var
bin/mount --move /proc /mnt/root/proc
bin/mount --move /sys /mnt/root/sys
bin/mount --move /dev /mnt/root/dev
echo "Executing switch_root..."
exec bin/switch_root /mnt/root /usr/lib/systemd/systemd-bootchart
